version: '3.8'

services:
  psychis-backend:
    build: .
    container_name: psychis_ai_server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
