import { generateDynamicKineticAnimation } from '../src/utils/kineticVisualGenerator';
import pendulum from './assets/app-pendulum.svg?raw';
import phasor from './assets/app-fourier.svg?raw';
// Primary subjects captured from the live app. Supporting notes are editorial, not search results.
export const groups=[['Research paths','stone'],['Oscillators','emerald'],['Signals','blue'],['Mathematical models','amber'],['Hearing','rose'],['Analysis','purple'],['Periodic patterns','teal'],['Listening','purple'],['Experiments','blue'],['Energy & response','emerald'],['Evidence & limits','stone'],['Reading notes','amber']];
const cards=[];
function card(id,title,description,x,y,group,o={}){const {type='spawned',formula,structure,...rest}=o;cards.push({id,x,y,group,type,data:{title,description,category:groups[group][0].toUpperCase(),status:'RESEARCH NOTE',source:'PSYCHIS / research notes',layout:{structure:structure||(formula?'formula_top':'minimal_quote')},...(formula?{formula}:{}),...rest}});}
function kinetic(title,formula,prompt){return generateDynamicKineticAnimation({data:{title,category:'physics',formula}},prompt).svg;}
card('intro','PSYCHIS','A space to think in connections.',960,425,0,{category:'SPATIAL KNOWLEDGE',status:'IDEA'});
card('source','Wave motion: a starting point','OpenStax · University Physics, Volume 1 · Chapter 16.',1048,487,0,{type:'website',url:'/animation/source.html',sourceUrl:'https://openstax.org/books/university-physics-volume-1/pages/16-introduction'});
card('spring','Undamped spring–mass oscillator','A restoring force exchanges elastic potential and kinetic energy. This ideal model neglects damping.',870,487,0,{structure:'kinetic_mechanism',gifSvg:kinetic('Undamped spring–mass oscillator','m x″ + k x = 0','spring'),formula:'m\\ddot{x}+kx=0',sourceCaptureId:'0x08',status:'IDEAL MODEL'});
card('pendulum','Simple pendulum','For small angles, the period depends on length and gravitational acceleration.',775,400,1,{structure:'split_formula',schemaSvg:pendulum.replaceAll('strokewidth','stroke-width').replaceAll('markerend','marker-end').replaceAll('strokedasharray','stroke-dasharray'),formula:'T\\simeq2\\pi\\sqrt{L/g}',sourceCaptureId:'0x06'});
card('damping','Damped spring–mass oscillator','A velocity-proportional resistive force removes mechanical energy.',765,506,1,{formula:'m\\ddot{x}+c\\dot{x}+kx=0',sourceCaptureId:'0x08'});
card('natural','Natural frequency','Mass and stiffness set the oscillator’s preferred angular frequency.',775,583,1,{formula:'\\omega_0=\\sqrt{k/m}'});
card('restoring','Restoring force','A displacement creates a force directed back toward equilibrium.',784,660,1,{formula:'F=-kx'});
card('packet','Wave packet: carrier and envelope','Phase and envelope may travel at different speeds. Group velocity is the slope of the dispersion relation.',1145,400,2,{structure:'kinetic_mechanism',gifSvg:kinetic('Wave packet: carrier and envelope','v_p = ω/k; v_g = dω/dk','wave packet'),formula:'v_g=\\frac{d\\omega}{dk}',sourceCaptureId:'0x09'});
card('fourier','Fourier transform & phasors','Resolve a signal into sinusoidal components. A rotating vector represents the phase of one component.',1150,505,2,{structure:'split_formula',schemaSvg:phasor,formula:'F(\\omega)=\\int_{-\\infty}^{\\infty}f(t)e^{-i\\omega t}dt',sourceCaptureId:'0x04'});
card('phase','Phase velocity','The speed of a point of constant phase is frequency divided by wave number.',1140,591,2,{formula:'v_p=\\omega/k'});
card('dispersion','Dispersion relation','Frequency-dependent propagation changes the relative phases within a packet.',1138,663,2,{formula:'\\omega=\\omega(k)'});
card('superposition','Superposition','In a linear system, add individual responses to obtain the total.',870,602,3,{formula:'y=y_1+y_2'});
card('wave-equation','The wave equation','A constant wave speed links spatial curvature and temporal acceleration.',966,592,3,{formula:'y_{tt}=v^2y_{xx}'});
card('wavelength','Wavelength and frequency','A traveling wave advances one wavelength during each period.',1055,608,3,{formula:'v=f\\lambda'});
card('standing','Standing-wave modes','Fixed endpoints admit wavelengths that fit the string’s length.',871,686,3,{formula:'f_n=\\frac{nv}{2L}'});
card('beats','Beats','Nearby frequencies produce a slowly varying amplitude envelope.',965,686,3,{formula:'f_b=|f_1-f_2|'});
card('interference','Constructive interference','Contributions reinforce when their phase difference is an integer multiple of a full turn.',1054,693,3,{formula:'\\Delta\\phi=2\\pi n'});
card('boundary','Boundary conditions','The allowed modes depend on what is fixed and what is free.',916,772,3);
card('linearity','Where the model applies','Superposition assumes a linear response. Large excursions can break that assumption.',1011,780,3,{type:'contradiction',thesis:'Every response is linear',antithesis:'Check amplitude and regime',source:'MODEL CHECK'});
card('cochlea','Cochlea & tonotopy','High frequencies peak nearer the base; lower frequencies peak nearer the apex.',801,179,4,{sourceCaptureId:'0x07'});
card('basilar','Basilar membrane','Its mechanical properties vary along the cochlea, shaping the traveling response.',771,263,4);
card('transduction','Mechanical to neural','Hair-cell deflection converts mechanical motion into an electrical response.',801,343,4);
card('spectrum','Frequency spectrum','A spectrum describes how a signal’s content is distributed across frequencies.',1120,164,5,{formula:'|F(\\omega)|'});
card('sampling','Sampling a signal','Samples must resolve the highest relevant frequency of a band-limited signal.',1153,252,5,{formula:'f_s>2f_{\\max}'});
card('aliasing','Aliasing','Undersampling can make different continuous signals produce the same samples.',1127,330,5,{type:'contradiction',thesis:'More detail than samples allow',antithesis:'Filter before sampling',source:'SIGNAL CHECK'});
card('period','Period','The time required for one complete repetition.',921,96,6,{formula:'T=1/f'});
card('angular','Angular frequency','Express repetition as angular progress per unit time.',1021,104,6,{formula:'\\omega=2\\pi f'});
card('phase-note','A shared mathematical language','Phase connects oscillation, wave propagation and signal analysis.',962,350,0);
card('music','Moonlight Sonata · string orchestra','Listen to an orchestral arrangement and compare sustained tones, attack and timbre.',420,535,7,{type:'music',layout:{structure:'music_card',width:390},sourceCaptureId:'0x01',musicData:{trackTitle:'Moonlight Sonata · I',artist:'Beethoven · Czech Symphony Orchestra',album:'Arrangement for string orchestra',year:'2025',genre:'Classical',duration:377,artwork:'/animation/assets/moonlight.jpg',previewUrl:'/animation/assets/silent.wav',fullAudioUrl:'/animation/assets/silent.wav'},source:'LISTENING EXAMPLE'});
card('timbre','Timbre','Two tones with the same fundamental can differ in their spectral content.',532,525,7);
card('envelope','Attack, sustain, decay','A note’s amplitude envelope contributes to how its sound is perceived.',444,640,7);
card('harmonics','Harmonic content','Overtones help distinguish a string tone from a simple sinusoid.',548,608,7,{formula:'f_n=nf_1'});
card('video','Wave reflection & standing waves','A classroom demonstration on a stretched medium provides a visual comparison with the ideal model.',1405,531,8,{type:'video',layout:{structure:'video_top',width:420},sourceCaptureId:'0x03',videoData:{videoId:'-n1d1rycvj4',title:'Wave Reflection and Standing Waves',thumbnail:'/animation/assets/standing-waves-video.jpg',platform:'youtube'},source:'VIDEO DEMONSTRATION'});
card('nodes','Nodes and antinodes','Some locations remain still while others oscillate with maximum amplitude.',1520,505,8);
card('measure','Measure before concluding','Compare predicted mode shapes with what the experiment shows.',1450,646,8,{type:'contradiction',thesis:'A diagram is a measurement',antithesis:'Test the prediction',source:'EVIDENCE CHECK'});
card('repeat','Repeatability','Repeat a measurement to distinguish a persistent pattern from noise.',1550,608,8);
card('energy','Energy exchange','Potential and kinetic energy alternate in an ideal oscillator.',690,642,9,{formula:'E=\\tfrac12kx^2+\\tfrac12mv^2'});
card('resonance','Resonance','A periodic drive can produce a strong response near a natural frequency.',602,670,9);
card('dissipation','Dissipation','Damping converts mechanical energy into other forms.',704,726,9,{formula:'\\frac{dE}{dt}=-c\\dot{x}^2'});
card('observe','Observation → model','Use a measured pattern to constrain a mathematical explanation.',1230,643,10);
card('uncertainty','Measurement uncertainty','Report a range appropriate to the instrument and method.',1316,685,10);
card('counterexample','Look for counterexamples','A useful model also makes clear where it can fail.',1225,740,10);
card('assumptions','State the assumptions','Small angles, linear forces and negligible losses are different approximations.',845,818,11);
card('sources','Keep the source connected','Link an explanation to the material that supports it.',950,857,11);
card('questions','A new question','Which features survive when the ideal assumptions are relaxed?',1100,824,11);
card('amplitude','Amplitude','Maximum displacement from equilibrium sets the scale of motion.',694,350,1,{formula:'|y|\\leq A'});
card('phase-difference','Relative phase','Phase differences determine how two periodic contributions combine.',1235,293,5,{formula:'\\Delta\\phi=\\phi_2-\\phi_1'});
card('filter','Frequency-selective response','A system can respond strongly to one range and weakly to another.',684,213,4);
card('representation','Time and frequency','Different representations reveal different properties of the same signal.',1225,157,5);
export const nodes=cards;
